### ISSUE TITLE
Segfault PHP 8.2

### ISSUE THREAD

**Issue by veewee** [veewee/ext-wasm#2]
On PHP 8.2 (on every OS), we get segfaults when running the testsuite:

> Run make phpunit
php "-d extension=./target/release/libext_wasm.so" ./tools/phpunit.phar;
PHPUnit 9.6.6 by Sebastian Bergmann and contributors.

> Segmentation fault (core dumped)
make: *** [Makefile:28: phpunit] Error 139
Error: Process completed with exit code 2.

See https://github.com/veewee/ext-wasm/pull/1

Possibly linked to https://github.com/davidcole1340/ext-php-rs/issues/218

**On mac:**

> make: *** [phpunit] Segmentation fault: 11

> The segmentation fault (signal 11) indicates an attempt to write to memory that has not been allocated to the process for writing. A common reason for this is when array bounds are exceeded.

**On Windows**

> mingw32-make: *** [makefile:29: phpunit] Error 2816

**Comment by sjsone** [comment]
Could it be the reason why this fails https://github.com/veewee/ext-wasm/blob/main/examples/function-multiple_arguments.php ?

**Comment by veewee** [comment]
No, that would be this one https://github.com/veewee/ext-wasm/issues/6. It should be a rather easy issue to solve imo.
On ubuntu 8.2, you get a segfault when running the unit tests (make phpunit)
Currently I only added one test, but all examples should preferably be tested.

In this issue, we'll have to debug what is going killing the php process.
But it might be related to the rs-php-ext issue linked above.

Normally all failures in the extension code are handled in a decent catchable exception.

(Maybe easier for me to follow what is going on if we both work with pull requests instead of pushing to main directly?)

**Comment by veewee** [comment]
Solved in ext-php-rs 0.10.1
